### ISSUE TITLE
Faster RCNN conversion

### ISSUE THREAD

**Issue by grzejszczakmarek** [TannerGilbert/Tensorflow-Lite-Object-Detection-with-the-Tensorflow-Object-Detection-API#2]
Hey there,
Great tutorial.
In the article and readme you are saying about conversion from faster RCNN to tflite. Were you succesful in that conversion?
I thought that only SSD models could be converted
Also in 2.1 step you are referint to 'export_tflite_ssd_graph.py' but the snippet is for 'export_inference_graph.py'. Those arent interchangeable for later conversion, correct?
Cheers

**Comment by TannerGilbert** [comment]
Actually the conversion doesn't work for FasterRCNN, only for SSD models as stated in the documentation. I'm sorry for putting false information in the README. Also the ```export_tflite_ssd_graph.py``` file should be used.

I changed both the README and Article. If you find any more errors let me know.
